import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Image from "next/image";
import Head from "next/head";
import Title from "@/components/Title";
import styles from'@/styles/ARSystem.module.css';
// import ARTest from "@/components/ARTest";

import dynamic from "next/dynamic";

const NoSSRARTest = dynamic(() => import("../components/ARTest"), {
  ssr: false,
});


// import { Image, Text, View } from "react-native";
export default function ARSystem({}) {

    const router = useRouter();
     const [params, setParams] = useState({});

   useEffect(() => {
     if (router.isReady) {
       console.log("ready", router.query);
       setParams(router.query);
     }
   }, [router.isReady]);
    return (
      <>
        <Head>
          <title>Mystery Mail</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Title></Title>
          {/* <div>
      {params?.image && <Image className={styles.image} src={params.image} width={200} height={200} alt={'Chosen image base for image tracking.'}></Image>}
        {params?.message && <p className={styles.text}>{params.message}</p>}
      </div> */}
          <NoSSRARTest></NoSSRARTest>
        </main>
      </>
    );
}